# Generated by Django 3.0.2 on 2020-02-10 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('subscribe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscribemodel',
            old_name='sys_id',
            new_name='id',
        ),
        migrations.CreateModel(
            name='ProjectsModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('projurl', models.TextField()),
                ('created_date', models.DateTimeField(blank=True)),
                ('status', models.TextField(default='active')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
            ],
            options={
                'db_table': 'gmw_projects',
            },
        ),
    ]
