# Generated by Django 3.0.2 on 2020-02-11 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0002_auto_20200210_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribemodel',
            name='level',
            field=models.CharField(max_length=20),
        ),
    ]
