# Generated by Django 2.2 on 2020-01-18 23:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0002_auto_20200117_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribemodel',
            name='status',
        ),
        migrations.AddField(
            model_name='subscribemodel',
            name='last_alert_for',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscribemodel',
            name='mail_count',
            field=models.IntegerField(default=0),
        ),
    ]
