# Generated by Django 3.0.2 on 2020-02-18 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0004_projectsmodel_data_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsmodel',
            name='projid',
            field=models.IntegerField(default=5346),
            preserve_default=False,
        ),
    ]
