# Generated by Django 3.0.2 on 2020-02-20 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200217_1844'),
        ('subscribe', '0005_projectsmodel_projid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsmodel',
            name='data_date',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='ExtractedData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('y', models.FloatField()),
                ('x', models.FloatField()),
                ('data_date', models.DateTimeField()),
                ('class_num', models.CharField(max_length=2)),
                ('class_name', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
            ],
            options={
                'db_table': 'gmw_extracted_data',
            },
        ),
    ]
