# Generated by Django 3.0.2 on 2020-04-12 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0006_auto_20200220_0653'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsmodel',
            name='name',
            field=models.TextField(default='Not Set'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectsmodel',
            name='regions',
            field=models.TextField(default='Previously selected regions'),
            preserve_default=False,
        ),
    ]
