# Generated by Django 3.1.7 on 2021-04-19 16:56

from django.db import migrations

def update_projurl(apps, schema_editor):
    ProjectsModel = apps.get_model('subscribe', 'ProjectsModel')
    for project in ProjectsModel.objects.all():
        project.projurl = project.projurl.replace("/collection", "/simple-collection")
        project.save()

class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0009_cronjobs_job_type'),
    ]

    operations = [
        migrations.RunPython(update_projurl),
    ]
