# Generated by Django 3.1.7 on 2021-04-20 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0010_auto_20210419_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='cronjobs',
            name='regions',
            field=models.TextField(default=''),
        ),
    ]
