# Generated by Django 3.1.7 on 2021-04-30 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0011_cronjobs_regions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribemodel',
            name='updated_date',
        ),
        migrations.AddField(
            model_name='extracteddata',
            name='data_layer',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='projectsmodel',
            name='data_layer',
            field=models.CharField(default='', max_length=25),
        ),
    ]
