# Generated by Django 3.1.7 on 2021-04-30 18:26

from django.db import migrations


def data_to_layer(apps, schema_editor):
    ProjectsModel = apps.get_model('subscribe', 'ProjectsModel')
    for project in ProjectsModel.objects.all():
        project.data_layer = project.data_date.strftime('%Y-%m-%d')
        project.save()
    ExtractedData = apps.get_model('subscribe', 'ExtractedData')
    for savedVal in ExtractedData.objects.all():
        savedVal.data_layer = savedVal.data_date.strftime('%Y-%m-%d')
        savedVal.save()


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0012_auto_20210430_1823'),
    ]

    operations = [
        migrations.RunPython(data_to_layer),
    ]
