# Generated by Django 3.1.7 on 2021-04-30 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0013_auto_20210430_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extracteddata',
            name='data_date',
        ),
        migrations.RemoveField(
            model_name='projectsmodel',
            name='data_date',
        ),
    ]
