# Generated by Django 3.1.7 on 2021-05-04 16:20

from django.db import migrations


def archive_dev(apps, schema_editor):
    ProjectsModel = apps.get_model('subscribe', 'ProjectsModel')
    for project in ProjectsModel.objects.all():
        if "ceodev" in project.projurl:
            project.status = 'archived'
            project.save()


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0014_auto_20210430_2056'),
    ]

    operations = [
        migrations.RunPython(archive_dev),
    ]
