# Generated by Django 3.1.7 on 2021-08-10 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0017_cronjobs_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='extracteddata',
            name='project_name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
