# Generated by Django 3.1.7 on 2022-02-11 22:28

from django.db import migrations

import re


def update_projurl(apps, schema_editor):
    ProjectsModel = apps.get_model('subscribe', 'ProjectsModel')
    for project in ProjectsModel.objects.all():
        project.projurl = re.sub('https://.*/', '/', project.projurl)
        project.save()


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0019_extracteddata_project.py'),
    ]

    operations = [
        migrations.RunPython(update_projurl),
    ]
