# Generated by Django 3.1.7 on 2021-05-06 16:04

from django.db import migrations, models


def combine_name(apps, schema_editor):
    Profile = apps.get_model('accounts', 'Profile')
    for user in Profile.objects.all():
        if user.full_name == "":
            combinedName = " ".join((user.first_name, user.middle_name,
                                     user.last_name, user.second_last_name))
            user.full_name = ' '.join(combinedName.split())
            user.save()
        # print(user.full_name == "")


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_full_name'),
    ]

    operations = [
        migrations.RunPython(combine_name),
    ]
