# Generated by Django 3.1.7 on 2021-05-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_combine_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='idnumber',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='idtype',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='second_last_name',
        ),
        migrations.AddField(
            model_name='profile',
            name='default_lang',
            field=models.CharField(default='es', max_length=4),
        ),
    ]
