# Generated by Django 3.1.7 on 2021-05-25 00:21

from django.db import migrations
from django.conf import settings


def to_lower(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    for user in User.objects.all():
        user.username = user.username.lower()
        user.email = user.email.lower()
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210519_1534'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(to_lower)
    ]
