DROP DATABASE IF EXISTS comimo;
DROP ROLE IF EXISTS comimo;
CREATE ROLE comimo WITH LOGIN CREATEDB PASSWORD 'comimo';
CREATE DATABASE comimo WITH OWNER comimo;
\c comimo
CREATE EXTENSION postgis;
CREATE EXTENSION pgcrypto;
